Spring Boot Versions matrix build (#48)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,11 +9,20 @@ on:
       - master
 
 jobs:
-  build:
-    name: "Build and Test"
+  matrix_build:
+    name: "Matrix Build"
     runs-on:
       - ubuntu-latest
+    strategy:
+      fail-fast: false
+      max-parallel: 100
+      matrix:
+        spring_boot_version:
+          - 2.7.6
+          - 2.6.14
+          - 2.5.14
     env:
+      SPRING_BOOT_VERSION: ${{ matrix.spring_boot_version }}
       GRADLE_OPTS: "-Djava.security.egd=file:/dev/./urandom -Dorg.gradle.parallel=true"
       IN_CI: true
       MARIADB_TCP_3306: 3306
@@ -62,9 +71,9 @@ jobs:
       - name: "Install packages"
         run: apt-get update && apt-get install -y git
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
       - name: "Gradle cache"
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
           path: |
             ~/.gradle
@@ -76,9 +85,10 @@ jobs:
       - name: "Test if publishing works"
         run: GRADLE_USER_HOME=$HOME/.gradle ./gradlew publishToMavenLocal --console=plain --no-daemon --stacktrace
       - name: "Publish Test Report"
-        uses: mikepenz/action-junit-report@v2
+        uses: mikepenz/action-junit-report@v3
         if: always()
         with:
+          check_name: Test Report-(${{ matrix.spring_boot_version }})
           report_paths: '**/build/test-results/**/*.xml'
           github_token: ${{ secrets.GITHUB_TOKEN }}
           require_tests: true
@@ -86,23 +96,46 @@ jobs:
         if: always()
         uses: jwgmeligmeyling/checkstyle-github-action@master
         with:
+          name: Checkstyle Report-(${{ matrix.spring_boot_version }})
           path: '**/build/reports/**/*.xml'
       - name: Publish spotbugs report
         if: failure()
         uses: jwgmeligmeyling/spotbugs-github-action@master
         with:
+          name: Spotbugs Report-(${{ matrix.spring_boot_version }})
           path: '**/build/reports/**/*.xml'
       - name: "Collect test reports"
         run: |
-          tar -zcvf all-test-reports.tar.gz **/build/reports
+          tar -zcvf all-test-reports-${{ matrix.spring_boot_version }}.tar.gz **/build/reports
         if: always()
       - name: "Store test results"
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3
         if: always()
         with:
-          name: all-test-reports
-          path: all-test-reports.tar.gz
+          name: all-test-reports-${{ matrix.spring_boot_version }}
+          path: all-test-reports-${{ matrix.spring_boot_version }}.tar.gz
           retention-days: 7
+        
+  build:
+    name: "Build and Test"
+    runs-on:
+      - ubuntu-latest
+    needs: matrix_build
+    steps:
+      # Needed hacks to properly fail the build when one matrix build fails.
+      - name: Do something so that GHA is happy
+        run: echo "Be happy!"
+      - name: Verify matrix jobs succeeded
+        if: ${{ needs.matrix_build.result != 'success' }}
+        run: exit 1
+      - name: Checkout repository
+        uses: actions/checkout@v3
+      - name: "Gradle cache"
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.gradle
+          key: gradle-v1-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', '**/*.gradle*') }}
       - name: "Tag release"
         if: github.ref == 'refs/heads/master'
-        run: GRADLE_USER_HOME=$HOME/.gradle ./gradlew tagRelease --console=plain --no-daemon
+        run: GRADLE_USER_HOME=$HOME/.gradle ./gradlew tagRelease --console=plain --info --stacktrace
